dist: bionic
language: cpp

compiler:
  - clang
  - gcc

install:
    - mkdir /tmp/vcpkg
    - cd /tmp/vcpkg
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - vckpkg install cryptopp

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=/tmp/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake

script:
    - make
