dist: bionic
language: cpp
sudo: true

compiler:
  - clang
  - gcc

install:
    - cd /tmp
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh -disableMetrics
    - ./vcpkg install cryptopp

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake

script:
    - make
